version: '3'

services:  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - mongo_db:/data/db

  node:
    build: . 
    ports:
      - 8088:8088
    container_name: docker-node-mongo
    restart: always
    links: 
      - mongo
    depends_on:
      - mongo

volumes:
  mongo_db: {}